
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-organic
owner: ucsb-cs156
repo_name: proj-organic
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"liquibase-v2","number":13,"title":"Liquibase v2","url":"https://github.com/ucsb-cs156/proj-organic/pull/13"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-fix-github-oauth-issues","number":12,"title":"pc - update security so that it doesn't crash when there's no email from github oauth","url":"https://github.com/ucsb-cs156/proj-organic/pull/12"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"mpriston-liquibase","number":9,"title":"Mpriston liquibase","url":"https://github.com/ucsb-cs156/proj-organic/pull/9"},{"author":{"id":"MDQ6VXNlcjIwODAwNjI5","is_bot":false,"login":"MPriston","name":"Matt Priston"},"headRefName":"main","number":5,"title":"Added Liquibase migrations","url":"https://github.com/ucsb-cs156/proj-organic/pull/5"}]
