
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-organic
owner: ucsb-cs156
repo_name: proj-organic
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"s24-5pm-2","number":68,"title":"s24-5pm-2","url":"https://github.com/ucsb-cs156/proj-organic/pull/68"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"s24-5pm-3","number":67,"title":"s24-5pm-3","url":"https://github.com/ucsb-cs156/proj-organic/pull/67"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"s24-5pm-4","number":66,"title":"s24-5pm-4","url":"https://github.com/ucsb-cs156/proj-organic/pull/66"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"s24-5pm-1","number":65,"title":"s24-5pm-1","url":"https://github.com/ucsb-cs156/proj-organic/pull/65"}]
